spring.application.name=FlywayDbMigration

# DB dev configuration [Replace with your actual credentials]
spring.datasource.url=jdbc:postgresql://<YOUR_RDS_ENDPOINT>:5432/<DB_NAME>
spring.datasource.username=<YOUR_USERNAME>
spring.datasource.password=<YOUR_PASSWORD>

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Flyway configuration
spring.flyway.baseline-on-migrate=false